name: Push on branch

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: --all -- --check
